services:
  db:
    image: postgres:alpine
    container_name: snippet-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5002:5432'
    volumes:
      - db-data-snippets:/var/lib/postgresql/data
volumes:
  db-data-snippets: