spring:
  application:
    name: ingsis-snippet

  datasource:
    url: jdbc:postgresql://localhost:5002/postgres-snippet
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}

auth0:
  audience: ${AUTH0_AUDIENCE}