spring:
  application:
    name: ingsis-snippet

  datasource:
    url: jdbc:postgresql://localhost:5002/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

auth0:
  audience: ${AUTH0_AUDIENCE}

server:
#  port: 80
  port: 8080


stream:
  lint.key: "lintRuleStream"
  format.key: "formatRuleStream"

groups:
  lint: "lintGroup"
  format: "formatGroup"