name: continuous deployment

on:
  workflow_call:
    inputs:
      actor:
        description: 'GitHub Actor'
        required: true
        type: string
      package_name:
        description: 'Package name to publish'
        required: true
        type: string
    secrets:
      token:
        description: 'Personal Access Token'
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Publish package
        run: ./gradlew publish --info
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          GITHUB_ACTOR: ${{ inputs.actor }}
          PACKAGE_NAME: ${{ inputs.package_name }}
